version: "3.8"

services:
  # BASES DE DATOS ------------------------------------------------------

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user_auth
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5434:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - pet-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  pet-db:
    image: postgres:15
    environment:
      POSTGRES_DB: pet_db
      POSTGRES_USER: user_pet
      POSTGRES_PASSWORD: pet_password
    ports:
      - "5433:5432"
    volumes:
      - pet_postgres_data:/var/lib/postgresql/data
    networks:
      - pet-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  match-db:
    image: postgres:15
    environment:
      POSTGRES_DB: match_db
      POSTGRES_USER: user_match
      POSTGRES_PASSWORD: match_password
    ports:
      - "5435:5432"
    volumes:
      - match_postgres_data:/var/lib/postgresql/data
    networks:
      - pet-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  notification-db:
    image: postgres:15
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: user_notif
      POSTGRES_PASSWORD: notif_password
    ports:
      - "5436:5432"
    volumes:
      - notif_postgres_data:/var/lib/postgresql/data
    networks:
      - pet-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  # MICROSERVICIOS ------------------------------------------------------

  auth-service:
    image: sanos-salvos-auth:latest
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: user_auth
      SPRING_DATASOURCE_PASSWORD: auth_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - pet-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  pet-service:
    image: sanos-salvos-petserv:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pet-db:5432/pet_db
      SPRING_DATASOURCE_USERNAME: user_pet
      SPRING_DATASOURCE_PASSWORD: pet_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      AUTH_SERVICE_URL: http://auth-service:8080
      MATCH_SERVICE_URL: http://match-service:8080
    networks:
      - pet-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  match-service:
    image: sanos-salvos-match:latest
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://match-db:5432/match_db
      SPRING_DATASOURCE_USERNAME: user_match
      SPRING_DATASOURCE_PASSWORD: match_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      PET_SERVICE_URL: http://pet-service:8080
      AUTH_SERVICE_URL: http://auth-service:8080
      NOTIFICATION_SERVICE_URL: http://notification-service:8080
    networks:
      - pet-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  notification-service:
    image: sanos-salvos-notif:latest
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/notification_db
      SPRING_DATASOURCE_USERNAME: user_notif
      SPRING_DATASOURCE_PASSWORD: notif_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - pet-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  # REDES ------------------------------------------------------

networks:
  pet-network:
    driver: overlay
    attachable: true

# VOLÚMENES ------------------------------------------------------

volumes:
  auth_postgres_data:
  pet_postgres_data:
  match_postgres_data:
  notif_postgres_data: