spring.application.name=notification-service
spring.datasource.url=jdbc:postgresql://sys-db:5432/sys_db
spring.datasource.username=user_sanos
spring.datasource.password=admin_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true